apiVersion: v1
kind: Secret
metadata:
  name: foodgram-secret
  namespace: mmproject
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-me-in-production-abc123xyz"
  POSTGRES_PASSWORD: "postgres"