apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mmproject
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migrate
          image: foodgram-backend:latest
          imagePullPolicy: Never
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: foodgram-config
            - secretRef:
                name: foodgram-secret
      containers:
        - name: backend
          image: foodgram-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: foodgram-config
            - secretRef:
                name: foodgram-secret
