# Generated by Django 5.2.3 on 2025-06-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_recipeingredient_recipeingridient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingridient',
            options={'verbose_name': 'Рецепт-Ингредиент', 'verbose_name_plural': 'Рецепт-Ингредиент-Список'},
        ),
    ]
