# Generated by Django 5.2.3 on 2025-06-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredients_remove_recipes_ingridients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipes'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_hash', models.CharField(max_length=10, unique=True, verbose_name='Короткий хеш')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipes.recipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
            },
        ),
    ]
