# Generated by Django 5.2.3 on 2025-06-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
